print('9'.isdigit())
print('9'.isalpha())
print('A'.isdigit())
print('A'.isalpha())
print('9'.isalnum())
print('B'.isalnum())
print('$'.isalnum())
print('python'.islower())
print('Python'.islower())
print('python'.isupper())
print('PYTHON'.isupper())
print('python is simple'.istitle())
print('Python Is Simple'.istitle())
